version: "3.4"

services:

  seednode:
    image: ${DOCKER_REGISTRY-}seednode
    build:
      context: .
      dockerfile: ./SeedNode/Dockerfile
    #image: petabridge/lighthouse:latest
    hostname: seednode
    ports:
      - '9200:19600'
      - '7053:4053'
    environment:
      CLUSTER_PORT: 4053
      CLUSTER_IP: "seednode"
      CLUSTER_SEEDS: "akka.tcp://actor-system@seednode:4053"
  
  singletonserver:
     image: ${DOCKER_REGISTRY-}singletonserver
     build:
      context: .
      dockerfile: ./SingletonAkka/SingletonServerApp/Dockerfile
     ports:
       - '0:9110'
     environment:
       #CLUSTER_PORT: 6500
       CLUSTER_SEEDS: "akka.tcp://actor-system@seednode:4053"
     depends_on:
       - "seednode"

  singletonclient:
     image: ${DOCKER_REGISTRY-}singletonclient
     build:
      context: .
      dockerfile: ./SingletonAkka/SingletonClientApp/Dockerfile
     ports:
       - '0:9110'
     environment:
       #CLUSTER_PORT: 6500
       CLUSTER_SEEDS: "akka.tcp://actor-system@seednode:4053"
     depends_on:
      - "seednode"