version: "3.4"
 
services:
  seednode:
    image: seednode:latest
    build:
      context: .
      dockerfile: ./SeedNode/Dockerfile
    hostname: seednode
    ports:
      - '19200:19600'
      #- '7053:4053'
    environment:
      CLUSTER_PORT: 4053
      CLUSTER_IP: "seednode"
      CLUSTER_SEEDS: "akka.tcp://actor-system@seednode:4053"

  tcpserver:
        image: tcpserver
        build:
           context: .
           dockerfile: AkkaTcpServer/Dockerfile
        ports:
           - 18878:19600
        environment: 
           CLUSTER_SEEDS: "akka.tcp://actor-system@seednode:4053"
        depends_on:
            - seednode
    